{{- if or .Values.ingress.issuer.enable (eq .Values.ingress.ingressClassName "haproxy") }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
  name: {{ .Release.Name }}-cert
spec:
  commonName: i3ray.nrp-nautilus.io
  dnsNames:
  - i3ray.nrp-nautilus.io
  issuerRef:
    kind: Issuer
    name: letsencrypt
  secretName: {{ .Release.Name }}-tls
{{- end }}

