apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentbit-config
data:
  fluent-bit.conf: |
    [INPUT]
        Name tail
        Path /tmp/ray/session_latest/logs/*
        Tag ray
        Path_Key true
        Refresh_Interval 5
    [FILTER]
        Name modify
        Match ray
        Rename true component_log
    {{ if eq .Values.fluentBit.output "victorialogs" }}
    [OUTPUT]
        Name                es
        Match               ray.raw
        Host                victorialogs.icecube.aq
        Port                443
        Path                insert/elasticsearch/
        Index               ray-logs
        Type                _doc
        Suppress_Type_Name  On
        Generate_ID         Off
        Header              VL-Time-Field date
        Header              VL-Msg-Field log
        Header              VL-Stream-Fields component_log
        tls                 On
    {{ else if eq .Values.fluentBit.output "stdout" }}
    [OUTPUT]
        Name stdout
        Match ray
        format json
