apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentbit-config
data:
  fluent-bit.conf: |
    [INPUT]
        Name tail
        Path /tmp/ray/session_latest/logs/*
        Tag ray
        Path_Key true
        Refresh_Interval 5
    [FILTER]
        Name modify
        Match ray
        Rename true component_log
    {{ if eq .Values.fluentBit.output "victorialogs" }}
    [OUTPUT]
        Name                http
        Match               *
        host                victorialogs.icecube.aq
        port                443
        uri                 /insert/jsonline?_stream_fields=stream&_msg_field=log&_time_field=date
        format              json_lines
        tls                 On
    {{ else if eq .Values.fluentBit.output "stdout" }}
    [OUTPUT]
        Name stdout
        Match ray
        format json
    {{ end }}
