apiVersion: ray.io/v1
kind: RayService
metadata:
  name: {{ .Release.Name }}-serve
  namespace: {{ .Release.Namespace }}
spec:
  serveConfigV2: |
    {{- toYaml .Values.serveConfig | nindent 4 }}
  serveService:
    metadata:
      name: {{ .Release.Name }}-serve
    spec:
      type: ClusterIP
      ports:
        - appProtocol: tcp
          name: serve
          port: 8000
          protocol: TCP
          targetPort: 8000
  rayClusterConfig:
    rayVersion: {{ .Values.global.rayVersion }}
    enableInTreeAutoscaling: true
    autoscalerOptions:
      upscalingMode: Default
      idleTimeoutSeconds: 60
      env:
        - name: AUTOSCALER_UPDATE_INTERVAL_S
          value: "5"
    headGroupSpec:
      rayStartParams:
        num-cpus: "0"
        num-gpus: "0"
      template:
        spec:
          containers:
          - name: ray-head
            image: {{ print .Values.global.image ":" .Values.global.imageTag }}
            imagePullPolicy: Always
            resources: {{ toYaml .Values.headGroupResources | nindent 14 }}
            volumeMounts:
            - name: cvmfs-volume
              mountPath:  /cvmfs
            - name: ray-logs
              mountPath: /tmp/ray
          - name: fluentbit
            image: fluent/fluent-bit:{{ .Values.fluentbit.imageTag }}
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 100m
                memory: 128Mi
            volumeMounts:
            - mountPath: /tmp/ray
              name: ray-logs
            - mountPath: /fluent-bit/etc/fluent-bit.conf
              subPath: fluent-bit.conf
              name: fluentbit-config 
          imagePullSecrets:
          - name: harbor-registry
          - name: dockerconfigjson-serviceaccount
          volumes:
          - name: cvmfs-volume
            {{- if eq .Values.global.cvmfs "persistentVolume" }}
            {{- include "cvmfsPersistentVolume" . | indent 12 }}
            {{- else if eq .Values.global.cvmfs "hostPath" }}
            {{- include "cvmfsHostPath" . | nindent 12 }}
            {{- end }}
          - name: ray-logs
            emptyDir: {}
          - name: fluentbit-config
            configMap:
              name: fluentbit-config
    workerGroupSpecs:
    - replicas: {{ .Values.scaling.podReplicas }}
      minReplicas: {{ .Values.scaling.minPodReplicas }}
      maxReplicas: {{ .Values.scaling.maxPodReplicas }}
      groupName: tasks
      rayStartParams: {}
      template:
        spec:
          containers:
          - name: ray-worker
            image: {{ print .Values.global.image ":" .Values.global.imageTag }} 
            imagePullPolicy: Always
            resources: {{ toYaml .Values.headGroupResources | nindent 14 }}
            volumeMounts:
            - name: cvmfs-volume
              mountPath:  /cvmfs
          imagePullSecrets:
          - name: harbor-registry
          - name: dockerconfigjson-serviceaccount
          volumes:
          - name: cvmfs-volume
            {{- if eq .Values.global.cvmfs "persistentVolume" }}
            {{- include "cvmfsPersistentVolume" . | indent 12 }}
            {{- else if eq .Values.global.cvmfs "hostPath" }}
            {{- include "cvmfsHostPath" . | indent 12 }}
            {{- end }}
