global:
  image: harbor.icecube.aq/wipac/i3_ray_serve
  imageTag: v0.4.3-alpha
  cvmfs: persistentVolume
  rayVersion: 2.52.0
  hostname: i3ray.nrp-nautilus.io
  clusterOnly: false
ingress:
  enable: true
  ingressClassName: haproxy
  rayMetrics:
    path: /metrics
    port: 8080
    enable: true
  issuer:
    enable: false
    issuerEmail: "admin@icecube.wisc.edu"
    issuerSecretName: issuer-account-key
gatewayAPI:
  enable: false
fluentBit:
  imageTag: 3.2.2
  output: victorialogs
serveConfig:
  applications:
    - name: i3_ray_serve
      route_prefix: /
      import_path: server:model
      deployments:
        - name: TglauchClassifier
          ray_actor_options:
            num-gpus: 1
            runtime_env:
              env_vars:
                LD_LIBRARY_PATH: ${LD_LIBRARY_PATH}:/home/ray/anaconda3/lib
          max_ongoing_requests: 50
          autoscaling_config:
            target_ongoing_requests: 5
            min_replicas: 5
            max_replicas: 25
env:
  LOG_LEVEL: INFO
  AUTH_AUDIENCE: ray-serve
  AUTH_OPENID_URL: https://keycloak.icecube.wisc.edu/auth/realms/IceCube
  MODEL_NAME: tglauch_classifier
  MODEL_VERSION: "3"
  MODEL_REPO: /cvmfs/icecube.opensciencegrid.org/users/briedel/ml/models
  MAX_BATCH_SIZE: 100
  BATCH_WAIT_TIMEOUT_S: 0.05
  EXECUTION_PROVIDER: CUDAExecutionProvider
volumeMounts:
  - name: cvmfs-volume
    mountPath: /cvmfs/icecube.opensciencegrid.org
    mountPropagation: HostToContainer
    subPath: icecube.opensciencegrid.org
headGroup:
  resources:
    limits:
      cpu: "3"
      memory: "8Gi"
    requests:
      cpu: "1"
      memory: "5G"
workerGroup:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                  - NVIDIA-A10
                  - NVIDIA-A40
                  - NVIDIA-L40S
                  - NVIDIA-L40
                  - Tesla-V100-SXM2-16GB
                  - Tesla-V100-SXM2-32GB
                  - Tesla-V100-PCIE-16GB
                  - Tesla-T4
  resources:
    limits:
      cpu: "6"
      memory: "15Gi"
      nvidia.com/gpu: 1
    requests:
      cpu: "5"
      memory: "10Gi"
      nvidia.com/gpu: 1
  scaling:
    podReplicas: 1
    minPodReplicas: 0
    maxPodReplicas: 10
metrics:
  localPrometheus:
    enable: true
    remoteWrite:
      - url: https://mimir.icecube.aq/api/v1/push
        headers:
          X-Scope-OrgID: prometheus
        name: mimir
  podMonitors:
    enable: false
